name: Update gist with WakaTime summary
on:
  schedule:
    - cron: '40 1 * * *'  # 每天 01:40 运行
  workflow_dispatch:  # 支持手动触发

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # 检出仓库
      - name: Update gist
        uses: superman66/wakatime-sync@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

      # 使用您自己的用户名和邮箱提交更改
      - name: Commit updated gist
        run: |
          git config --global user.name "wisdomgo" 
          git config --global user.email "1246045735@qq.com"
          git add .
          # 检查是否有需要提交的更改
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update gist with WakaTime summary"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用自动生成的 GitHub Token
