name: Update gist with WakaTime summary
on:
  schedule:
    - cron: '40 1 * * *'  # 每天 01:40 运行
  workflow_dispatch:  # 支持手动触发

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # 检出仓库
      - name: Update gist
        uses: superman66/wakatime-sync@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

      # 添加一个步骤来提交和推送更改
      - name: Commit updated gist
        run: |
          git config --global wisdomgo "github-actions[bot]"
          git config --global 1246045735@qq.com "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update gist with WakaTime summary"
          git push
        env:
          # 使用 GitHub 提供的自动生成的 token 进行推送
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
