name: Update gist with WakaTime summary
on:
  schedule:
    - cron: '40 1 * * *'
  workflow_dispatch:  # 添加此行以支持手动触发
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: wisdomgo/wakatime-sync@node16
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID}}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SCU_KEY: ${{ secrets.SCU_KEY }}
